### ISSUE TITLE
Updating Website

### ISSUE THREAD

**Issue by iamSleepl3ss** [iamSleepl3ss/BO19-G05#10]
## Title
Update website with better navigation/entry page.

| Note|
|:----------|
| The website for the project is a little bit make-shifted, even though it is beautiful. It already has WordPress so we can utilize OceanWP and Elementor and just make a very quick makeshift website. Aleksander and Bahar can take a look at this if you want.    |

### Tasks
- [ ] Task 1: Choose a better theme?
- [ ] Task 2: Make a better introductory and blog page.
- [ ] Task 3: Make a better project/landing page.
- [ ] Task 4: Any security? Honestly, just make it look finesse. You know what I'm sayin'? 👍 💯 :-)
_Worth nothing that this Issue is not that urgent!!._

### Description.
Just fresh up the website in general you know?

### Result
Anybody that wants to can help. If any necessary changes has to be made, the whole group has to know about it!

### Ekstra informasjon
_Take a look at Google or awwwards for inspiration._
