### ISSUE TITLE
Sizarta has to check our preliminary report.

### ISSUE THREAD

**Issue by iamSleepl3ss** [iamSleepl3ss/BO19-G05#11]
## Preliminary report check-up
Checking group G05's preliminary report.

### Tasks
- [x] Task 1: Check what more is necessary to be added to the report.
- [x] Task 2: Is there something grammatically wrong?
- [x] Task 3: Are we lacking something, or is there something we should necessarily add or update to the report for now? 
- [x] Task 4: Does the structure hold up, or is it necessary for adjustments to the structure and flow? 
_None of these are a must, these are just some examples we could also get feedback on. If this sounds like a bit too abrasive then feel free to give us any feedback you'd like really! _

### Description
Group 05 has to hand in a pre-project report. This has to be updated before it is put into the final report.

### That's it. really. 

thanks Sizarta!
