### ISSUE TITLE
Tema for app

### ISSUE THREAD

**Issue by iamSleepl3ss** [iamSleepl3ss/BO19-G05#12]
## Skisser for tema til prosjekt.

| Notat|
|:----------|
| Ta en titt på www.behance.com for ideer | 

### Tasks
- [x] Task 1 :  Bahar and Aleksander must take time to compete, and come up with different suggestions for the design-theme.
- [x] Task 2 : While doing this, also take notes for functionality. 
- [x] Task 3 : Make two easy wireframes. 

### Beskrivelse
Vi må skisse appen og få en generel idee om hvordan temaet skal være. 

### Løsningsforslag
Vi tegner lol.

**Comment by iamSleepl3ss** [comment]
Et over-ordnet tema er valgt, men flere valg er fortsatt mulig for hvordan tema-et skal utvikles. 
Evt send ut spørreundersøkelser til Posten, PostNord, https://postkom.no/ og andre pakke-leveranse. (Komplett.no)
