### ISSUE TITLE
Møteinnkalling 7.02.2019

### ISSUE THREAD

**Issue by baharseyhan** [iamSleepl3ss/BO19-G05#14]
# Møteinnkalling 7.02.2019
***7.02.2019

## Time and Place
08:30 - 10:00
A2-216

## Pre-planning
Everybody has to have an idea of what the want the app to look like. We everyone to have an idea of how will look like, and the minimum functionality requirements. Use-cases and "kravspekk" should be the result for this. 
Function --> Methodology --> Kravspekk. 

## Tasks
- [x] Task 1 - What more has to be specified in the theme and design? A more detailed review and argumentative about our choices in the theme.
- [x] Task 2 - Take a look at app-designs. What would be more effective? Discuss. What should we incorporate into our own app?
- [x] Task 2.5 - Sketch, talk and come to the minimum requirements for our design too.
- [x] Task 3 - Surveys. Take a look at the potential sources in the comments of issue #13. Make an issue for it, but push it till after Theme and Functionality is set. Can we also ask a teacher in "Interaction Design"? (Joakim Karlsen).
- [x] Task 4 - We need Wireframes for the 4 main pages from issue #13 and one for the hub page too. We also need 2 pictures in fully colored theme presentation, this will be used for the Prototype much later. 

## Extra
We need to find themes. Then present them in the meeting. What more needs to be specified about the Design. Arguments about it would be great! The next meeting we have to come to a conclusion about how the theme will look, so Bahar and Aleksander can start making Wireframes and sketches for the "Prototype" and surveys. From there on out we also have to declare the minimum-solutions so we can add it to the survey. Then, send out the surveys while we finally decide on a report-template.  
Function --> Methodology --> Kravspekk.

**Comment by iamSleepl3ss** [comment]
https://docs.google.com/document/d/1VkkJKHPlTb5-C7Cg5ZVlS9vRJ5wkTVi9RzZxUFNmwGw/edit
