### ISSUE TITLE
Sketches and Wireframes for prototype

### ISSUE THREAD

**Issue by iamSleepl3ss** [iamSleepl3ss/BO19-G05#15]
## Sketches and Wireframes for prototype
We need sketches to show in our surveys, asking other corporations for what functionality they see missing. A wireframe for the Hub and another tab would be great! 

| Note!|
|:----------|
| www.figma.com 
www.draw.io |

### Tasks
- [ ] Task 1 - Take a look at issue #9, #12, and #14's meeting summary. 
- [ ] Task 2 - We need 4 wireframes and 2 theme-presentations in total. 
- [ ] Task 3 - Use draw.io to draw the planned placements of the function buttons in the wireframes. Think about user-friendly designs. 
- [ ] Task 4 - Use any kind of digital drawing program to sketch up how the app will look. 
- [ ] Task 5 - Try to make an interact-able prototype in Figma. This could become our Prototype and is necessary for the main document. 

### Description
The problem now is to finalize and get all the functions and what we've talked about together. We need to get a rough overview of what the app will look like, so we can show these during interviews/surveys and get feedback for necessary adjustments. 

### Solution
Bahar and Aleksander will draw two wireframes each, thinking about the placements of the buttons and elements. Think about what we talking about during the #14 issue. Incorporate into both the function, then do the sleek design that Dennis and Aleksander had in mind. Take huge inspiration from Dennis and look at the sketches in google drive.
https://drive.google.com/drive/folders/1l0CUi9ZGCcBkBrv8t2G9ddlP5jcXReSl

### Extra
_Make it look Prada._
